export const FETCH_STORE_REVIEWS = "FETCH_STORE_REVIEWS";
export const CREATE_STORE_REVIEW = "CREATE_STORE_REVIEW";
export const CHANGE_SEARCH = "CHANGE_SEARCH"
export const GET_RESULTS = "GET_RESULTS"
